# Generated by Django 5.2.17 on 2026-09-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('severity', models.CharField(max_length=50)),
            ],
        ),
    ]
